repository: Virgers/Virgers.github.io
favicon: images/web-logo.ico

# Content configuration version
version: 2

# Personal info
name: Jinlong Huo
title: 3rd-year master student of XJTU&Polimi
email: jinlong.huo99@gmail.com
# website: https://virgers.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Virgers

# About Section
# about_title: About Me
about_profile_image: images/profile_Jinlong.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Jinlong and I'm a third-year Xi'an Jiaotong University and Politecnico di Milano graduate. Currently, I am focusing on using ML to interpret seismic profiles, especially using Transformer models.
  I am most interested in: <mark>LLM</mark> potential combination with specific domains, like <mark>geophysics</mark>. I am also willing to work on bio-electronics interface or SoC since I think it is the best way to combine singals, hardware and AI.


content:
  - title: Education
    layout: list
    content:
      - layout: left
        title: BS Xinjiang University
        caption: 2018 - 2022
        sub_title: BSc Telecommunication
        description: |
          Lucky was to collaborate with a very nice group of teammates to learn, have fun, stay up late, and compete for common goals.  *[Check our video at that year to compete with HIT :).](https://www.bilibili.com/video/BV1Hw411R7RT/?spm_id_from=333.999.0.0)* and *[recordings in Chinese](https://drive.google.com/file/d/1luu99C7Dx86RGLgOmt9gwhMDMNoUszfe/view?usp=drive_link)*(*[English Version](https://drive.google.com/file/d/1mQQ8JyBS1uplRr9EQqvSDcmDhJfgsThv/view?usp=drive_link)*). Despite the loss of a set, we managed to win the match strategically and advance to the quarterfinals. 
          
          This experience ignited my interest in research further. I learned basic programming skills, how to combine theory and practical robotics performance, how to communicate in a team, how to manage time, and how to devote one's spirit to focus on one thing.

      - layout: left
        title: MS Xi'an Jiaotong University & Politecnico di Milano
        caption: 2022 - present
        sub_title: Msc Telecommunication
        description: |
          Luckily again, I was selected to enroll in a double-degree exchange program at Polimi! It was such an experience that it consolidated my mind to pursue further research. During this period, I've done many projects and noticed the differences between them, from teaching to management, from incentive self-development to passive acceptance.
          
          Such different educational environments aroused my curiosity about how to conduct research scientifically and systematically. I want to formulate my own.
      # quote: > Treat people as an end, and never as a means to an end. It's the same for study.


  - title: Research Interests  # Title for the section
    layout: list
    content:
      - layout: top-middle
        # border: weak
        title: Click the button. It's a more complete CV with more courses works lol.
        # link: BELOW
        additional_links:
          - title: JinlongHuo/CV
            icon: fab fa-github
            url: https://drive.google.com/file/d/1oSLu4eRn3JEuEimQ3ssdTl_0VU7hEzwN/view?usp=drive_link
        quote: >
          Immanuel Kant: Act to treat humanity, whether in your person or in that of another, at all times also as an end, and not only as a means.

        description: |
          Most of my published works have been accomplished in the field of geophysics by applying machine learning methods at XJTU. Regrettably, I consider myself someone who merely utilizes them, even though it might some sense with certain topics. I feel compelled to delve deeper to uncover the philosophy underlying both artificial intelligence and applied fields. Sometimes, the process is more significant than the results.
          
          Currently, I'm interested in the application of LLM in geophysics or, more generally, their potential in the interpretation of other domain-specific vocabularies, such as seismic profiles, sensor readings, medical data, biological sequences, etc., which have rich semantic content and interpretable patterns. More importantly, they should have an adequate volume of training data. Fundamentally, this idea originates from this series of papers: *[Physics of Language Models](https://physics.allen-zhu.com/)* by Zeyuan Allen-Zhu. The insightful design of context-free kindles the plausibility of the hypothesis that LLM can understand data. <mark>If artificially designed context-free data can be interpreted well, accordingly, it's reasonable to infer that other natural scientific data could also be interpreted.</mark> The quote by Kant is also applicable to the study itself. That is to say, for me, I truly believe LLM works.


  - title: A Little More About Me
    layout: text
    content: |
      Alongside my study, some of my other interests and hobbies are:
      - Climbing
      - Travelling
      - Watching Movies
      - *[Check out some travel diaries before.:)](https://cherry-devourer-bd2.notion.site/Europe-39d823a355d04325a41483de7963cff4)* Hope someday I'll update them lol.
      
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
