# # Site
# repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# # favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# # Personal info
# name: Edward Xia
# title: IT Project Engineer
# email: vigoose@gmail.com
# phone: 201-783-9068
# website: https://vigoose.github.io/online-cv/

# # Social links
# twitter_username: vigoose
# github_username:  vigoose
# facebook_username: vigoose.xia
# instagram_username: vigoose
# linkedin_username: yuanyexia


# # About Section
# # about_title: About Me (Use this to override about section title)
# about_profile_image: images/fullsizeoil_profile_photo2-426-edit-edit_002.JPG
# about_content: | # this will include new lines to allow paragraphs
#   Hi My name is Edward and I am a Software Engineer currently live in Redwood City, CA, below are some highlights of myself:
#    - Two Master degrees in Information Systems with Six year IT-specific projects experience. 
#    - Software Engineer in Full Stack development with strong problem-solving ability and business analysis skills.          
    
      
#   I like <mark>Challenging Work</mark> also a <mark>Beef Lover</mark>.

# # Experience Section
# # experience_title: Experience #(Use this to override about experience section title)

# # Projects Section
# # projects_title: Projects #(Use this to override about projects section title)

# # Education Section
# # education_title: Education #(Use this to override about education section title)

# # More Section
# # more_title: A Little More About Me #(Use this to override about more section title)
# more_content: | # this will include new lines to allow paragraphs
#   Love basketball, music, anime, also a HardCore Gamer, interested in everything that might interesting, people empathy oriented.

# # Footer
# footer_show_references: true

# # Build settings
# # theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# # remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

# sass:
#   sass_dir: _sass
#   style: compressed

# plugins:
#  - jekyll-seo-tag
# Site

repository: sproogen/resume-theme
favicon: images/web-logo.ico

# Content configuration version
version: 2

# Personal info
name: Jinlong Huo
# title: Senior Network System Administrator
email: jinlong.huo99@gmail.com
website: https://virgers.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  Virgers
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_Jinlong.png
about_content: | # this will include new lines to allow paragraphs
 Hi, my name's Jinlong and I'm a third year graduate in Xi'an Jiaotong University and Politecnico di Milano. Currently, I am focusing on using ML to interpret seismic profiles, especially using Transformer models.
  I am most interested in: <mark>LLM</mark> potential combination with specific domains, like <mark>geophysics<mark>. I also willing to work on bio-electronics interface or SoC, since I think it is the best way to combine singals, hardware and AI.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Some projects
        link: github.com/Virgers
        # link_text: Project Website
        additional_links:
          - title:  Jinlong's repository
            icon: fab fa-github
            url: github.com/Virgers
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
          # This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        # description: | # this will include new lines to allow paragraphs
          # I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  # - title: Experience # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: The Boring Company
  #       link: boringcompany.com
  #       # link_text: boringcompany.com
  #       sub_title: Senior Network System Administrator
  #       caption: November 2017 - Present
  #       quote: >
  #         Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
  #       description: | # this will include new lines to allow paragraphs
  #           Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  # - title: Education # Title for the section
  #   layout: list # Type of content section (list/text)
  #   content:
  #     - layout: left
  #       title: Harvard University
  #       caption: 2010 - 2013
  #       sub_title: BSc Computer Science
  #       quote: >
  #         Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
  #       description: | # this will include new lines to allow paragraphs
  #         During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  #         I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

    # - title: Education # Title for the section
    # layout: list # Type of content section (list/text)
    # content:
    #   - layout: left
    #     title: BS Xinjiang University # Harvard University
    #     caption: 2018 - 2022
    #     sub_title: BSc Telecommunication
    #     # quote: >
    #       # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
    #     description: | # this will include new lines to allow paragraphs

    #     Lucky was I to collobarate with very nice group of teammates to learn, have fun, stay up late, and compete for common goals.  *Check our vedio at that year to compete with HIT :).(https://www.bilibili.com/video/BV1Hw411R7RT/?spm_id_from=333.999.0.0)* Despite the loss of a set, we managed to win the match strategically and advance to the quarterfinals. 
    #     This experience serves as the fundamental to ignite my interest to research further. I learnt basic skills to program, to combine theory and practical robotics performance, how to communicate in a team, how to manage time, how to devote one's spirit to foucs on one thing.

#         - layout: left
#         title: MS Xi'an Jiaotong University & Politecnico di Milano
#         caption: 2022 - present
#         sub_title: Msc Telecommunication
#         # quote: >
#           # Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
#         description: | # this will include new lines to allow paragraphs
#         Lucky again, I was selected to enroll double degree exchange program to Polimi! It was such experience consolidate my mind to pursue for further research. Through this period, I've done many projects and notice the differences between them, from teaching to management, from incentive self-development to passive acceptance
# . Such different educational environments arouse my curiosity about how to scientifically and systematically conduct a research. I want to formulate mine.
#         Most of my published works have done in geophysics using machine learning methods as well as other projects. Saddly, I assume myself as a person who only use them, even though makes little sense regarding some certain topics. I found myself or obliged to delve into more to uncover the philosphy behind both artificical intelligence and applied fileds. Sometimes, it is process matters over results. Like Kant said
#         # quote: > Treat people as an end, and never as a means to an end. It's same for study.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
